[tool.poetry]
name = "Python-Chatbot"
version = "0.1.0"
description = "A chatbot that you can talk to when you're bored."
authors = ["RLX <contactrlxop@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]

[build-system]